version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout:
          path: /home/ubuntu/fringe
      - run:
          name: Setup Miniconda
          command: |
            set -ex
            apt update
            apt install -y wget make
            apt-get update --yes && apt-get upgrade --yes
            cd /home/ubuntu
            wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
            bash miniconda.sh -b -p /home/ubuntu/miniconda
            source /home/ubuntu/miniconda/etc/profile.d/conda.sh
            conda activate base
            conda env create -f fringe/docs/environment_linux.yml
      - run:
          name: Install FRInGE
          command: |
            set -ex
            source /home/ubuntu/miniconda/etc/profile.d/conda.sh
            conda activate fringe
            cd /home/ubuntu 
            mkdir build install
            cd build
            cmake -DCMAKE_INSTALL_PREFIX=../install ../fringe
            make install

      - run:
          name: Test FRInGE
          command: |
              set -ex
              source /home/ubuntu/miniconda/etc/profile.d/conda.sh
              conda activate fringe
              export PATH="/home/ubuntu/install/bin:$PATH"
              export PYTHONPATH="/home/ubuntu/install/python:$PYTHONPATH"
              export LD_LIBRARY_PATH="/home/ubuntu/install/lib:$LD_LIBRARY_PATH"
              evd.py -h
              nmap.py -h
              ampdispersion.py -h
              python3 /home/ubuntu/fringe/tests/evd/test_evd.py
